//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangra.TangraService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TangraService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name errorInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportError", ReplyAction="*")]
        Tangra.TangraService.ReportErrorResponse ReportError(Tangra.TangraService.ReportErrorRequest request);
        
        // CODEGEN: Generating message contract since element name errorInfo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportErrorWithAttachment", ReplyAction="*")]
        Tangra.TangraService.ReportErrorWithAttachmentResponse ReportErrorWithAttachment(Tangra.TangraService.ReportErrorWithAttachmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportError", Namespace="http://tempuri.org/", Order=0)]
        public Tangra.TangraService.ReportErrorRequestBody Body;
        
        public ReportErrorRequest() {
        }
        
        public ReportErrorRequest(Tangra.TangraService.ReportErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errorInfo;
        
        public ReportErrorRequestBody() {
        }
        
        public ReportErrorRequestBody(string errorInfo) {
            this.errorInfo = errorInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tangra.TangraService.ReportErrorResponseBody Body;
        
        public ReportErrorResponse() {
        }
        
        public ReportErrorResponse(Tangra.TangraService.ReportErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReportErrorResponseBody {
        
        public ReportErrorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorWithAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorWithAttachment", Namespace="http://tempuri.org/", Order=0)]
        public Tangra.TangraService.ReportErrorWithAttachmentRequestBody Body;
        
        public ReportErrorWithAttachmentRequest() {
        }
        
        public ReportErrorWithAttachmentRequest(Tangra.TangraService.ReportErrorWithAttachmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportErrorWithAttachmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errorInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string attName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] attContent;
        
        public ReportErrorWithAttachmentRequestBody() {
        }
        
        public ReportErrorWithAttachmentRequestBody(string errorInfo, string attName, byte[] attContent) {
            this.errorInfo = errorInfo;
            this.attName = attName;
            this.attContent = attContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportErrorWithAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportErrorWithAttachmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Tangra.TangraService.ReportErrorWithAttachmentResponseBody Body;
        
        public ReportErrorWithAttachmentResponse() {
        }
        
        public ReportErrorWithAttachmentResponse(Tangra.TangraService.ReportErrorWithAttachmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReportErrorWithAttachmentResponseBody {
        
        public ReportErrorWithAttachmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Tangra.TangraService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Tangra.TangraService.ServiceSoap>, Tangra.TangraService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tangra.TangraService.ReportErrorResponse Tangra.TangraService.ServiceSoap.ReportError(Tangra.TangraService.ReportErrorRequest request) {
            return base.Channel.ReportError(request);
        }
        
        public void ReportError(string errorInfo) {
            Tangra.TangraService.ReportErrorRequest inValue = new Tangra.TangraService.ReportErrorRequest();
            inValue.Body = new Tangra.TangraService.ReportErrorRequestBody();
            inValue.Body.errorInfo = errorInfo;
            Tangra.TangraService.ReportErrorResponse retVal = ((Tangra.TangraService.ServiceSoap)(this)).ReportError(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Tangra.TangraService.ReportErrorWithAttachmentResponse Tangra.TangraService.ServiceSoap.ReportErrorWithAttachment(Tangra.TangraService.ReportErrorWithAttachmentRequest request) {
            return base.Channel.ReportErrorWithAttachment(request);
        }
        
        public void ReportErrorWithAttachment(string errorInfo, string attName, byte[] attContent) {
            Tangra.TangraService.ReportErrorWithAttachmentRequest inValue = new Tangra.TangraService.ReportErrorWithAttachmentRequest();
            inValue.Body = new Tangra.TangraService.ReportErrorWithAttachmentRequestBody();
            inValue.Body.errorInfo = errorInfo;
            inValue.Body.attName = attName;
            inValue.Body.attContent = attContent;
            Tangra.TangraService.ReportErrorWithAttachmentResponse retVal = ((Tangra.TangraService.ServiceSoap)(this)).ReportErrorWithAttachment(inValue);
        }
    }
}
